
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/container-storage-interface/spec/lib/go",
]

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "v0.2.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.5.2"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/freddierice/go-losetup.v1"
